config/routes.rb
Rails.application.routes.draw do
  
  root 'schedules#index'
  resources :schedules

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  default_scope -> { order(updated_at: :desc) }
  
  validates :title, presence: true
  validates :start, presence: true
  validates :end, presence: true
  validates :memo, length:{maximum: 255}
  
  validate :end_start_check
  validate :start_check, on: :create
    
  def end_start_check
    return if self.start.blank?
      errors.add(:end, "は開始日時より遅い日時を選択してください") if self.start > self.end
  end
  
  def start_check
    return if self.end.blank? || self.start.blank?
      errors.add(:start, "は現在の日時より遅い日時を選択してください") if self.start < Time.now.floor_to(10.minutes)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all
  end

  def show
    @schedule = Schedule.find(params[:id])
  end

  def new
    @schedule = Schedule.new
  end
  
  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      flash[:notice] = "スケジュールを新規作成しました"
      redirect_to :schedules
    else 
      flash.now[:alert] = "スケジュールを作成できませんでした"
      render "new"
    end
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end
  
  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(schedule_params)
      flash[:notice] = "スケジュールを編集しました"
      redirect_to :schedules
    else
      flash.now[:alert] = "スケジュールを編集できませんでした"
      render "edit"
    end
  end
  
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    flash[:notice] = "スケジュールを削除しました。"
    redirect_to :schedules
  end
  
  private
  def schedule_params
    params.require(:schedule).permit(:title, :priority, :start, :end, :all_day, :memo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <main class="main_container">
      <%= yield %>
    </main>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/schedules/edit.html.erb
<h2>スケジュール編集</h2>

<%= render "shared/flash" %>
<%= render "shared/error_message", obj:@schedule %>

<%= form_with model: @schedule do |f| %>
  <table>
    <tr>
      <th><%= f.label :title, "タイトル" %></th>
      <td><%= f.text_field :title %></td>
    </tr>
    <tr>
      <th><%= f.label :priority, "優先度" %></th>
      <td>
        <%= f.radio_button :priority, "高" %>高
        <%= f.radio_button :priority, "中" %>中
        <%= f.radio_button :priority, "低", checked: true %>低
      </td>
    </tr>
    <tr>
      <th><%= f.label :start, "開始日時" %></th>
      <td><%= f.datetime_field :start %></td>
    </tr>
    <tr>
      <th><%= f.label :end, "終了日時" %></th>
      <td><%= f.datetime_field :end %></td>
    </tr>
    <tr>
      <th><%= f.label :all_day, "終日" %></th>
      <td><%= f.check_box :all_day %>終日の場合はチェックを入れます</td>
    </tr>    
    <tr>
      <th><%= f.label :memo, "スケジュールメモ" %></th>
      <td><%= f.text_area :memo, size: "30x6" %></td>
    </tr>
  </table>
  <div>
    <ul>
      <li><%= f.submit "スケジュールの編集を完了する" %></li>
      <li><%= link_to "スケジュール一覧に戻る", :schedules %></li>
    </ul>
  </div>
<% end %>

app/views/schedules/index.html.erb
<h2>スケジュール一覧</h2>

<%= render "shared/flash" %>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>優先度</th>
      <th>開始日時</th>
      <th>終了日時</th>
      <th>終日</th>
      <th>更新日時</th>
      <th>確認</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>
  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.id %></td>
        <td><%= schedule.title %></td>
        <td><%= schedule.priority %></td>
        <td><%= schedule.start.to_s(:datetime_jp) %></td>
        <td><%= schedule.end.to_s(:datetime_jp) %></td>
        <td><% if schedule.all_day == true %> ◯ <% end %></td>
        <td><%= schedule.updated_at.to_s(:datetime_jp) %></td>
        <td><%= link_to "確認", schedule %></td>
        <td><%= link_to "編集", edit_schedule_path(schedule) %></td>
        <td><%= link_to "削除", schedule, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to "スケジュール新規作成", :new_schedule %></p>

app/views/schedules/new.html.erb
<h2>スケジュール新規作成</h2>

<%= render "shared/flash" %>
<%= render "shared/error_message", obj:@schedule %>

<%= form_with model: @schedule do |f| %>
  <table>
    <tr>
      <th><%= f.label :title, "タイトル" %></th>
      <td><%= f.text_field :title %></td>
    </tr>
    <tr>
      <th><%= f.label :priority, "優先度" %></th>
      <td>
        <%= f.radio_button :priority, "高" %>高
        <%= f.radio_button :priority, "中" %>中
        <%= f.radio_button :priority, "低", checked: true %>低
      </td>
    </tr>
    <tr>
      <th><%= f.label :start, "開始日時" %></th>
      <td><%= f.datetime_field :start %></td>
    </tr>
    <tr>
      <th><%= f.label :end, "終了日時" %></th>
      <td><%= f.datetime_field :end %></td>
    </tr>
    <tr>
      <th><%= f.label :all_day, "終日" %></th>
      <td><%= f.check_box :all_day %>終日の場合はチェックを入れます</td>
    </tr>
    <tr>
      <th><%= f.label :memo, "スケジュールメモ" %></th>
      <td><%= f.text_area :memo, size: "30x6" %></td>
    </tr>
  </table>
  
  <div>
    <ul>
      <li><%= f.submit "スケジュールを新規登録する"%></li>
      <li><%= link_to "スケジュール一覧に戻る", :schedules %></li>
    </ul>
  </div>
<% end %>

app/views/schedules/show.html.erb
<h2>スケジュール詳細</h2>

<table>
  <tr>
    <th>タイトル</th>
    <td><%= @schedule.title %></td>
  </tr>
  <tr>
    <th>優先度</th>
    <td><%= @schedule.priority %></td>
  </tr>
  <tr>
    <th>開始日時</th>
    <td><%= @schedule.start.to_s(:datetime_jp) %></td>
  </tr>
  <tr>
    <th>終了日時</th>
    <td><%= @schedule.end.to_s(:datetime_jp) %></td>
  </tr>
  <tr>
    <th>終日</th>
    <td><% if @schedule.all_day == true %> ◯ <% end %></td>
  </tr>
  <tr>
    <th>更新日時</th>
    <td><%= @schedule.updated_at.to_s(:datetime_jp) %></td>
  </tr>
  <tr>
    <th>メモ</th>
    <td><%= @schedule.memo %></td>
  </tr>
</table>

<div>
  <ul>
    <li><%= link_to "スケジュール一覧に戻る", :schedules %></li>
    <li><%= link_to "スケジュールを編集する", [:edit, @schedule] %></li>
    <li><%= link_to "スケジュールを削除する", @schedule, method: :delete, data: { confirm: "本当に削除しますか？" } %></li>
  </ul>
</div>

app/views/shared/_error_message.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li class="error"><%= message %></li>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% if flash.alert %>
  <p class="flash_alert"><%= flash.alert %></p>
<% end %>


<% if flash.notice %>
  <p class="flash_notice"><%= flash.notice %></p>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <h1>
  <%= "現在の日時：#{Time.current.to_s(:y_datetime_jp)}" %>
  <% if @schedules %>
    <span><%= "スケジュール合計：#{@schedules.count}" %></span>
  <% end %>
  </h1>
</footer>

app/views/shared/_header.html.erb
<header>
  <h1>Ruby on Rails スケジュール管理アプリ</h1>
</header>